---
- name: Create main directory
  file:
    path: '{{ user_directory }}/.{{chain}}'
    state: directory
    mode: '0755'

- name: Create config directory
  file:
    path: '{{ user_directory }}/.{{chain}}/config'
    state: directory
    mode: '0755'

- name: Copy binary
  copy:
    remote_src: true
    src: '{{ user_directory }}/hyperlane-monorepo/rust/target/release/validator'
    dest: '{{ user_directory }}/.{{chain}}/hyperlane_validator'
    mode: '0775'

- name: Copy agent config file
  copy:
    src: '{{ chain }}.json'
    dest: '{{ user_directory }}/.{{chain}}/config/agent-config.json'
    mode: '0664'

- name: Compile env file
  template:
    src: 'env.txt'
    dest: '{{ user_directory }}/.{{chain}}/.env'
    mode: '0664'

- name: Compile service file
  become: true
  template:
    src: 'hyperlane.service'
    dest: '/etc/systemd/system/{{ chain }}.service'
    owner: root
    group: root
    mode: '0644'

- name: start service
  become: true
  systemd:
    name: '{{ chain }}'
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: additional actions needed
  debug:
    msg: 'Please edit the .env file and replace those TBD fields and then restart the service'
