name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - maissacrement
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: make build-stable

  check:
    name: Syntax Check
    runs-on: ubuntu-latest
    container:
      image: maissacrement/ansibledind:10e77ca-stable
      options: --entrypoint="/home/entrypoint.sh run" --privileged -u root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Ansible Syntax Check
        run: >
          ansible-playbook --connection=local 127.0.0.1 --syntax-check hyperlane.yml --extra-vars "ansible_role_include_tasks=true"

  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    container:
      image: maissacrement/ansibledind:10e77ca-stable
      options: --entrypoint="/home/entrypoint.sh run" --privileged -u root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Ansible Lint
        run: ansible-lint -vv
