name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  check:
    name: Syntax Check
    runs-on: ubuntu-latest
    container:
      image: maissacrement/ansibledind:10e77ca-stable
      options: --entrypoint="/home/entrypoint.sh run" --privileged -u root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Ansible Syntax Check
        run: >
          ansible-playbook --connection=local -i localhost, --syntax-check \
            -e "target=localhost" --extra-vars "ansible_role_include_tasks=true" \
          hyperlane.yml

  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    container:
      image: maissacrement/ansibledind:10e77ca-stable
      options: --entrypoint="/home/entrypoint.sh run" --privileged -u root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Ansible Lint
        run: ansible-lint -vv
